### PR TITLE
Fix #375

### LINKED ISSUE #375: Shoud check for ascending series should apply to stop_times of the interval?
I have the following situation:

```
sleep_states = nwbfile.processing["behavior"]["SleepStates"]
sleep_states.to_dataframe().head(8)
```

Which outputs the following:

| id | start_time | stop_time | label                |
|----|------------|-----------|----------------------|
|  0 |          1 |         1 | WAKEtheta_ThDt       |
|  1 |          1 |         3 | QWake_ThDt           |
|  2 |          1 |         3 | QWake_noRipples_ThDt |
|  3 |          1 |        50 | WAKEnontheta         |
|  4 |          1 |       100 | WAKEstate            |
|  5 |          3 |         4 | WAKEtheta_ThDt       |
|  6 |          5 |        13 | QWake_ThDt           |
|  7 |          5 |        13 | QWake_noRipples_ThDt |

And it is flagged by the inspector with the following warning:
```
0.1  fCamk1_200827_sess9.nwb: check_time_interval_time_columns - 'TimeIntervals' object with name 'SleepStates'
       Message: ['stop_time'] are time columns but the values are not in ascending order. All times should be in seconds with respect to the session start time.
```

Looking at the check it seems that it assumes that all time columns should be ascending which does not seem to be true for my case. 

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/2ddada2cf7481127d35616ece0e6e7d17e332d29/src/nwbinspector/checks/tables.py#L47-L71

Am I missing something? What do you think?

### PR DESCRIPTION
**Pull request by h-mayorquin**
This should fix #375. 

Give the discussion in #375 this should probably be the only function that is checked. All the other time columns might not be in ascending order for perfectbly acceptable reasons I think.

### CODE REVIEW

**Comment by bendichter** [comment]
@h-mayorquin looks like you'll have to adjust the tests as well

**Comment by CodyCBakerPhD** [comment]
And CHANGELOG please 👍

**Comment by h-mayorquin** [comment]
Yep.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Thanks!

**Pull request merged**
