### PR TITLE
Bump Numpy version

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
## Motivation

From https://github.com/dandi/dandi-cli/pull/1143#issuecomment-1355512856, trying to update requirements for `numpy`

### CODE REVIEW

**Comment by bendichter** [comment]
I'm fine with loosening our restriction on numpy, but I think the best way to address that issue is to test for Python 3.11.

**Comment by CodyCBakerPhD** [comment]
Does PyNWB do that yet?

**Comment by CodyCBakerPhD** [comment]
Also this is really just pushing the buck up to PyNWB anyway: https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/setup.py#L24 

Just making it so we don't have to track them exactly here every time they bump the upper bound

**Comment by CodyCBakerPhD** [comment]
Similar to https://github.com/catalystneuro/neuroconv/pull/234, awaiting word that `h5py` supports 3.11 (last check as of 2 weeks ago says no builds available: https://github.com/catalystneuro/neuroconv/actions/runs/3569661856/jobs/5999836476)

**Comment by bendichter** [comment]
It looks like we should start with hdmf, which does not yet test against 3.11

https://github.com/hdmf-dev/hdmf/blob/dev/.github/workflows/run_all_tests.yml

**Review by bendichter — APPROVED** [review]

**Pull request merged**
