### PR TITLE
Update DANDI dev tests

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Follow-up from the relaxation of installation requirements related to DANDI usage in #490 

Should hopefully fix the mystery issue (and overall improvements along the way)

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Quite oddly, it has also shown up on dailies now: https://github.com/NeurodataWithoutBorders/nwbinspector/actions/runs/10721955376

following merge of #490, and they were passing before then: https://github.com/NeurodataWithoutBorders/nwbinspector/actions/workflows/dailies.yml

Doesn't necessarily mean that PR caused it - could have been something else that occurred around the same time

I tried to reproduce locally but have been unable to

**Comment by CodyCBakerPhD** [comment]
Aha: culprit identified - the `3.14.4` release of HDMF

**Comment by CodyCBakerPhD** [comment]
@stephprince OK figured out the issue here and notified upstream

**Review by stephprince — APPROVED** [review]
Looks good to me!

**Pull request merged**
