### PR TITLE
Generic outer level progress bar control

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@garrettmflynn You should be able to use this draft branch to try out the approach for the Inspector

Right now there would just be one progress bar tracking the number of files left to be scanned

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Yep this works great!

**Comment by garrettmflynn** [comment]
This PR is no longer functional with the GUIDE and requires https://github.com/NeurodataWithoutBorders/nwbinspector/pull/443 to be merged in.

**Comment by CodyCBakerPhD** [comment]
The GUIDE specifically doesn't utilize this particular route, but it might still be useful

Or are you saying something overlooked here actually causes a problem with the GUIDE?

**Comment by garrettmflynn** [comment]
There isn't a corresponding PR on the GUIDE that works solely for this. https://github.com/NeurodataWithoutBorders/nwb-guide/pull/676 has been refactored to work with https://github.com/NeurodataWithoutBorders/nwbinspector/pull/443, but will fail when using this PR alone.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Yes, I know. GUIDE specifically needs the next step of this chain

But is there an actual problem with the actual part of the code in the PR?

**Review by garrettmflynn — APPROVED** [review]
Ah sure, this implementation is fine. 

However you'd like to coordinate the merge is fine with me. Feel free to start here!

**Pull request merged**
