### PR TITLE
[Feature]: Generalized Formatting

### LINKED ISSUE #109: [Documentation]: add documentation for display_messages_by_importance
https://github.com/NeurodataWithoutBorders/nwbinspector/blob/262ef38176a3dbbb1ccbeddd57687fc92cdda5ed/nwbinspector/inspector_tools.py#L61

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
## Motivation

A while back we generalized the organization function to allow any hierarchical structure based on an ordering of `InspectorMessage` attributes called `levels`, but we only had two static displays the enforced particular instances of organizing.

This introduces the corresponding generalized formatting for any type of organization.

It also exposes this to the CLI.

I've attached two examples of current output, both illustrating the automated way of doing the current static displays: [by_file_importance.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8344751/by_file_importance.txt)
[by_importance_checkname_file.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8344752/by_importance_checkname_file.txt)

One thing I wanted to bring up though, is if `levels` is the best name for communicating this, especially on the CLI. Other candidate argument/flag names could be `order_by`, `organize_by`, `sort_by`, to more closely reflect the intended behavior that, for an example comparison, corresponds to imposing ordering rules on columns of some spreadsheet whose rows are being sorted (our 'rows' being individual inspector messages and their attributes.

## To-Do

- [x] Use class based approach with functional wrapper
- [x] separate detailed vs. simplified output when last level is `file_path`
- [x] ~~disallow object name, couple with type~~ displays type -> name pattern whenever both are not levels
- [x] add version of package (and by way, registry) to total header
- [x] add .rst style headers for first three levels
- [x] Add `reverse` to CLI as well?
- [x] Need to fix tests, mainly by setting the new ground truth examples to the updated format 
- [x] Add documentation illustrating usage (see PR #147)

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Example usage on DANDISet `000004` (with `skip_validate=False`): [example_organize_000004.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8344784/example_organize_000004.txt)

**Comment by bendichter** [comment]
looks great!

**Comment by CodyCBakerPhD** [comment]
@bendichter Here are a number of example outputs for the new formatter. I'll work on documenting general usage of this tonight.

Once I get your confirmation that these look OK, I'll update the failing tests to use the new ground truth. (Would be annoying to have to do this multiple times for any changes you want made based on the examples).

[000004_check_name_file_path_simple_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392820/000004_check_name_file_path_simple_new_format.txt)
[000004_importance_file_path_detailed_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392821/000004_importance_file_path_detailed_new_format.txt)
[000004_importance_file_path_reversed_simple_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392822/000004_importance_file_path_reversed_simple_new_format.txt)
[000004_importance_file_path_simple_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392823/000004_importance_file_path_simple_new_format.txt)
[000004_importance_object_type_check_name_file_path_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392824/000004_importance_object_type_check_name_file_path_new_format.txt)

**Comment by bendichter** [comment]
The reports look good! I like [000004_importance_file_path_simple_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392823/000004_importance_file_path_simple_new_format.txt) the best.

**Comment by CodyCBakerPhD** [comment]
> The reports look good! I like [000004_importance_file_path_simple_new_format.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8392823/000004_importance_file_path_simple_new_format.txt) the best.

👍 me too, that's why I second that as the default. But I can also see situations where some of the others might be better on a case-by-case basis. But for any violations common across all all files in a directory and spanning multiple importances, the new view is vastly superior.

I'll work on the tests now

**Comment by CodyCBakerPhD** [comment]
@bendichter Ready for review now. I do understand this is a rather large PR and the code is fairly complicated. I've tried to make it as efficient, non-redundant, flexible, and readable as possible, but please take your time looking over it and I'll address any questions/issues next week.

Cheers!

**Review by bendichter — APPROVED** [review]

**Pull request merged**
