### PR TITLE
Fix testing suite for PyNWB v2.1.0

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Discovered from #218, fixed here. Raised also in https://github.com/NeurodataWithoutBorders/pynwb/issues/1497

### CODE REVIEW

**Comment by bendichter** [comment]
If you want to remove x, y, and z, you'll need to set the pynwb requirement to >= 2.1.0

**Comment by CodyCBakerPhD** [comment]
> If you want to remove x, y, and z, you'll need to set the pynwb requirement to >= 2.1.0

Note that the removal is purely for testing purposes, and testing always performs using latest requirements without having to enforce the minimal install on others. That said it's also not intended behavior so I expect them to fix it quite soon anyway. No change to core behavior is expected for our checks w.r.t <= 2.1.0

**Comment by bendichter** [comment]
>  testing always performs using latest requirements without having to enforce the minimal install on others

what do you mean?

If I run `pytest` on my local machine, it won't be guaranteed to run the latest version of every package

**Comment by CodyCBakerPhD** [comment]
> If I run pytest on my local machine, it won't be guaranteed to run the latest version of every package

I was narrowly thinking about only the CI workflows that use fresh installs of all the most recent dependencies unless an upper bound is applied.

I can see how that would be limiting for local testing, though, so swapped with a `pytest.skipIf` condition that will be removed once the upstream issue is fixed.

**Pull request closed without merging**
