### PR TITLE
changes to dataset compression check

### LINKED ISSUE #52: problem with compression test
This is showing up for many datasets:

```
BEST PRACTICE VIOLATION
-----------------------
1.1.1   NWBFile 'root' located in '/'
        check_dataset_compression: Consider enabling compression when writing a large dataset.
```
It's not clear what dataset is causing the violation.

### PR DESCRIPTION
**Pull request by bendichter**
fix #52 

* only activate warning when the dataset is > 1GB
* change warning from violation to suggestion
* include field name in inspector message

## Motivation

What was the reasoning behind this change? Please explain the changes briefly.

## How to test the behavior?
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/nwbinspector/pulls) for the same change?
- [x] Is your code contribution compliant with `black` format? If not, simply `pip install black` and run `black .` inside your fork.
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
> only activate warning when the dataset is > 1GB

I'll take a second to investigate what is triggering the issue; depending on what it is, 1GB might be a bit larger than necessary to make this a non-issue, but I'm not against setting a hard lower bound on triggering this.

> change warning from violation to suggestion

I'm against this, suggestions are the lowest priority items but it's possible for a dataset that triggered this to be extremely large. Also, if we're already setting a lower bound to yield more accurate (and therefore fewer) trigger scenarios, then the situations where it does flag this would thus be more important.

Also, I get that when we add the DANDI `intention` feature it will escalate something like this to `CRITICAL`, most likely, but I still think as a default practice it should be given higher due consideration than missing metadata.

> include field name in inspector message

Great change.

**Comment by CodyCBakerPhD** [comment]
Some suggestions and tests fixes: https://github.com/NeurodataWithoutBorders/nwbinspector/pull/54

**Comment by bendichter** [comment]
@CodyCBakerPhD can you fix this path issue?

**Comment by bendichter** [comment]
I may have messed things up when I resolved a merge conflict

**Comment by CodyCBakerPhD** [comment]
@bendichter fixed

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
