### PR TITLE
Add retry for curl requests

### LINKED ISSUE #197: [Bug]: Can't read data (curl cannot perform request)
### What happened?

As I parse the remaining errors from the first attempt to inspect the entire archive, a number of repetitions of this issue occur. One basic example is in the traceback section below, but I've also attached all report files where it occurs, which spans multiple objects.

There also seem to be some related issues such as `ConstructErrors` and `KeyError: 'Unable to open object by token (unable to determine object type)'`.

In each of these cases, I am streaming the data via `ros3`, which could very well be a part of the problem. Interestingly, sometimes these curl errors occur outside of the `nwbfile = io.read() step` which causes the the dandiset to not be inspectable at all (which I'm considering a separate issue).

Anyway here is the full set of tracebacks available in the ERROR sections of each report...

[000008.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543040/000008.txt)
[000011.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543041/000011.txt)
[000035.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543042/000035.txt)
[000041.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543043/000041.txt)
[000043.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543044/000043.txt)
[000054.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543045/000054.txt)
[000121.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543047/000121.txt)
[000148.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543048/000148.txt)
[000211.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543051/000211.txt)
[000223.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543053/000223.txt)

### Steps to Reproduce

_No response_

### Traceback

```shell
0.0  <class 'OSError'>: Can't read data (curl cannot perform request)
---------------------------------------------------------------------

0.0.0  sub-mouse-GHNSF/sub-mouse-GHNSF_ses-20190828-sample-3_slice-20190828-slice-3_cell-20190828-sample-3_icephys.nwb: 'None' object with name 'None'
         Message: Traceback (most recent call last):
  File "/home/jovyan/GitHub/nwbinspector/nwbinspector/nwbinspector.py", line 476, in inspect_nwb
    nwbfile = io.read()
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 498, in read
    return call_docval_func(super().read, kwargs)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/utils.py", line 424, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/io.py", line 37, in read
    f_builder = self.read_builder()
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 515, in read_builder
    f_builder = self.__read_group(self.__file, ROOT_NAME, ignore=ignore)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 656, in __read_group
    builder = read_method(sub_h5obj)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 656, in __read_group
    builder = read_method(sub_h5obj)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 656, in __read_group
    builder = read_method(sub_h5obj)
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 683, in __read_dataset
    scalar = h5obj[()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jovyan/my-conda-envs/nwbct_3_9/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 775, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: Can't read data (curl cannot perform request)
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.9

### Package Versions

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
fix #197 

Attempting to resolve curl requests errors to S3 paths, up to `max_retries` using the suggested exponential back-off

### CODE REVIEW

**Comment by bendichter** [comment]
I think this looks good but perhaps we need an importable function that can help users do this

**Comment by CodyCBakerPhD** [comment]
> I think this looks good but perhaps we need an importable function that can help users do this

I was toying around with some ways to do that; it was proving a tad tricky since the user (or ourselves) might wish to call any executable code on the open `io` handling the S3 requests - but my idea was to make a context class that does something like

```python
with retry_s3_call(max_retries=10):
    # try to do something on an open io
```

where the thing you try to do could be as simple as `nwbfile = io.read()` or `run_some_check_on_nwbfile(nwbfile=nwbfile)` etc, but wasn't sure how to construct such a context capable of running arbitrary code multiple times (or a function for that matter).

**Comment by CodyCBakerPhD** [comment]
Though I suppose that a context is simply not possible for that kind of thing... https://stackoverflow.com/a/64770597

Perhaps a simple function like

```python
def try_until_success(command, attempts=1):
    for _ in range(attempts):
        try:
            return command()
        except Exception as exc:
            err = exc

    raise err
```

might work (from https://stackoverflow.com/a/64770679)

**Comment by bendichter** [comment]
yeah that would be cool but I don't know if that's possible. Usually contexts pass in an object that is used within the context, e.g.

```python
with open("fpath", "r") as f:
    # use f here
```

I think the best approach might be to do two things:
1. adjust `NWBHDF5IO` to use retries if driver == "ros3"
2. create a `robust_read` function that can be used like 

```python
robust_read(nwbfile.acquisition["ElectricalSeries"].data, slice(1, 10), max_retries=5)
```
what do you think?

**Comment by bendichter** [comment]
One tricky thing is that the HDF5 Datasets themselves don't have information about whether they are s3 or local. I can't think of a way to automatically switch to retrying if ros3 is being used. I suppose we could just always retry, but even that is tricky because we are interfacing with the h5py.Dataset objects directly. There are lots of ways we could potentially approach this. Let's discuss in our meeting today.

**Comment by CodyCBakerPhD** [comment]
> I suppose we could just always retry

That's what I've done in latest commit using a very similar function to what you outlined in `2.` above. It shouldn't hurt in the non-S3 case since it will just execute and return the output nonetheless on first try (or first `retry`).

Could also put in switch at the corresponding deployment levels to determine whether to do it at the classic way or S3 way.

Will discuss this later, then.

**Review by bendichter — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Summary: this patch is fine for now, it hits most of the major error points where this can occur - long term solution is to support `s3fs` through PyNWB and that should automatically handle this kind of thing much better (and offer improved performance) but only downside is Windows would still have to go through `ros3`.

Otherwise, a more sophisticated approach would be a decorator that wraps functions in the registry (and `io.read()`) and does more or less the same thing as this utility but would therefore allow less awkward function `arg`/`kwarg` passing.

**Pull request merged**
