### PR TITLE
Proposal for a logo for the NWBInsepctor

### PR DESCRIPTION
**Pull request by oruebel**
## Motivation

I figured it would be nice to have a logo for the NWBInspector. This PR is a proposal for a logo. Feel free to reject the PR if you don't like the logo or let me know how I should change the logo. 

## Checklist

- [X] Have you ensured the PR description clearly describes the problem and solutions?
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/nwbinspector/pulls) for the same change?
- [X] Is your code contribution compliant with `black` format? If not, simply `pip install black` and run `black .` inside your fork.
- [X] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by bendichter** [comment]
Cool! @CodyCBakerPhD , what do you think?

**Comment by CodyCBakerPhD** [comment]
@oruebel Oh wow, I love it!

Do you happen to have a vector-graphic (`.eps`, `.pdf`, etc.) version available, or only the `.png` raster? I'm always a fan of the former since it's resolution is independent of the zoom aspect, but NBD if not.

**Comment by rly** [comment]
Looks great!

**Comment by oruebel** [comment]
> Do you happen to have a vector-graphic (`.eps`, `.pdf`, etc.)

I updated the PowerPoint to use the PDF vector graphic of the NWB brain logo and exported the logo to PDF as well. I moved the files to a separate folder, so there are now: 1) the PowerPoint file I used to create the logo, 2) PNG of the logo, and 3) PDF of the logo.

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
> I updated the PowerPoint to use the PDF vector graphic of the NWB brain logo and exported the logo to PDF as well. I moved the files to a separate folder, so there are now: 1) the PowerPoint file I used to create the logo, 2) PNG of the logo, and 3) PDF of the logo.

Awesome!! Thanks a bunch

**Pull request merged**
