### PR TITLE
Dynamic table unique ids

### PR DESCRIPTION
**Pull request by bendichter**
## Motivation

What was the reasoning behind this change? Please explain the changes briefly.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
LGTM - did you check this against the NeuroNexus file?

**Comment by bendichter** [comment]
> LGTM - did you check this against the NeuroNexus file?

yup., it catches it

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
> yup., it catches it

Great, can you write or update a best practices section in the docs for it as well? In that section it can be mentioned that the easiest solution is often to try updating the PyNWB version. For custom DynamicTables obviously the user has full control over that kind of stuff, but this violation came from something that old PyNWB versions generated automatically through convenience functions like the first call to `add_electrodes`

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Codecov v3 has had problems uploading on occasion - feel free to ignore and merge or otherwise retrigger it and hope for the best

**Pull request merged**
